name: GitHub Actions tests
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  GitHub-Actions-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js 20.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      - name: npm install, npm test
        run: |
          npm install
          npm test

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
